//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18010
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 [&quot;北京&quot;,&quot;101010100&quot;]
        ///[&quot;海淀&quot;,&quot;101010200&quot;]
        ///[&quot;朝阳&quot;,&quot;101010300&quot;]
        ///[&quot;顺义&quot;,&quot;101010400&quot;]
        ///[&quot;怀柔&quot;,&quot;101010500&quot;]
        ///[&quot;通州&quot;,&quot;101010600&quot;]
        ///[&quot;昌平&quot;,&quot;101010700&quot;]
        ///[&quot;延庆&quot;,&quot;101010800&quot;]
        ///[&quot;丰台&quot;,&quot;101010900&quot;]
        ///[&quot;石景山&quot;,&quot;101011000&quot;]
        ///[&quot;大兴&quot;,&quot;101011100&quot;]
        ///[&quot;房山&quot;,&quot;101011200&quot;]
        ///[&quot;密云&quot;,&quot;101011300&quot;]
        ///[&quot;门头沟&quot;,&quot;101011400&quot;]
        ///[&quot;平谷&quot;,&quot;101011500&quot;]
        ///[&quot;八达岭&quot;,&quot;101011600&quot;]
        ///[&quot;佛爷顶&quot;,&quot;101011700&quot;]
        ///[&quot;汤河口&quot;,&quot;101011800&quot;]
        ///[&quot;密云上甸子&quot;,&quot;101011900&quot;]
        ///[&quot;斋堂&quot;,&quot;101012000&quot;]
        ///[&quot;霞云岭&quot;,&quot;101012100&quot;]
        ///[&quot;上海&quot;,&quot;101020100&quot;]
        ///[&quot;闵行&quot;,&quot;101020200&quot;]
        ///[&quot;宝山&quot;,&quot;101020300&quot;]
        ///[&quot;川沙&quot;,&quot;101020400&quot;]
        ///[&quot;嘉 [字符... 的本地化字符串。
        /// </summary>
        internal static string DefaultCode {
            get {
                return ResourceManager.GetString("DefaultCode", resourceCulture);
            }
        }
    }
}
