//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18010
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace personid.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("personid.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 [{&quot;110000&quot;:&quot;北京市&quot;},        ///{&quot;110100&quot;:&quot;北京市市辖区&quot;},        ///{&quot;110101&quot;:&quot;北京市东城区&quot;},        ///{&quot;110102&quot;:&quot;北京市西城区&quot;},        ///{&quot;110103&quot;:&quot;北京市崇文区&quot;},        ///{&quot;110104&quot;:&quot;北京市宣武区&quot;},        ///{&quot;110105&quot;:&quot;北京市朝阳区&quot;},        ///{&quot;110106&quot;:&quot;北京市丰台区&quot;},        ///{&quot;110107&quot;:&quot;北京市石景山区&quot;},        ///{&quot;110108&quot;:&quot;北京市海淀区&quot;},        ///{&quot;110109&quot;:&quot;北京市门头沟区&quot;},        ///{&quot;110111&quot;:&quot;北京市房山区&quot;},        ///{&quot;110112&quot;:&quot;北京市通州区&quot;},        ///{&quot;110113&quot;:&quot;北京市顺义区&quot;},        ///{&quot;110200&quot;:&quot;北京市县&quot;},        ///{&quot;110221&quot;:&quot;北京市昌平县&quot;},        ///{&quot;110224&quot;:&quot;北京市大兴县&quot;},        ///{&quot;110226&quot;:&quot;北京市平谷县&quot;},        ///{&quot;110227&quot;:&quot;北京市怀柔县&quot;},        ///{&quot;110228&quot;:&quot;北京市密云县&quot;},        ///{&quot;110229&quot;:&quot;北京市延庆县&quot;},        ///{&quot;120000&quot;:&quot;天津市&quot;},        ///{&quot;120100&quot;:&quot;天津市市辖区&quot;},        ///{&quot;120101&quot;:&quot;天津市和平区&quot;},        ///{&quot;120102&quot;:&quot;天津 [字符串的其余部分被截断]... 的本地化字符串。
        /// </summary>
        internal static string station {
            get {
                return ResourceManager.GetString("station", resourceCulture);
            }
        }
    }
}
